_JAVA_HOME="/Users/nicola/Library/Java/JavaVirtualMachines/corretto-11.0.10/Contents/Home"
_DEV_DB_USERNAME=root
_DEV_DB_PASSWORD=123456
_DEV_DB_URL=jdbc:mysql://localhost:3306/moopsy
GOOGLE_CLIENT_ID=AAAAxxAr1LA:APA91bF1F8Jy5KbC-8g_iMETXJ1lwNqMn_QJkclvi8d2yX41La6_F_AAfyPh0RKZtCvRUzlhdEk_muBcIEv9Of0dNDNb6bqgx4lOmRfZyDcmkuOU7OcJJCjqaxAEwSWNxtvEJqJZIm__
export JAVA_HOME=$_JAVA_HOME
